# Generated by Django 5.1.7 on 2025-03-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(default='Unknown', max_length=20, unique=True)),
                ('book_title', models.CharField(default='Unknown', max_length=255)),
                ('book_author', models.CharField(default='Unknown', max_length=255)),
                ('year_of_publication', models.IntegerField(default=2000)),
                ('publisher', models.CharField(default='Unknown', max_length=255)),
                ('image_url', models.URLField(blank=True, default='', null=True)),
            ],
        ),
    ]
